# Draft a metadata.yaml skeleton from a stats.swiss data structure definition.
#
#   Rscript inst/build_metadata.R DF_PASTA_552_MONTHLY
#
# Writes data-raw/metadata.draft.yaml. The draft carries the structural part
# only -- title, dim_order, hierarchy and labels, in all four languages. The
# judgement calls (which SDMX dimension becomes which OpenTSI dimension name,
# units, aggregation rules, code renamings such as "_T" -> "tot", details) stay
# with the maintainer: diff the draft against data-raw/metadata.yaml and port
# what changed. See docs/PLAYBOOK.md section 4.

devtools::load_all(quiet = TRUE)

args <- commandArgs(trailingOnly = TRUE)
flow_id <- if (length(args)) args[[1]] else PASTA_FLOW_ID
langs <- c("en", "de", "fr", "it")

message("Reading codelists for ", flow_id)
cl <- lapply(langs, function(lg) sse_codelists(flow_id, lang = lg))
names(cl) <- langs

base <- cl[["en"]]
# FREQ selects the dataset's frequency rather than forming part of the key.
dims <- setdiff(unique(base$dimension), c("FREQ", "TIME_PERIOD"))

label_block <- function(code, indent) {
  pad <- strrep(" ", indent)
  vals <- vapply(langs, function(lg) {
    hit <- cl[[lg]]$label[cl[[lg]]$code == code]
    if (length(hit)) hit[[1]] else NA_character_
  }, character(1))
  c(sprintf("%s'%s':", pad, code),
    sprintf('%s  %s: "%s"', pad, langs, gsub('"', "'", vals)))
}

out <- c(
  "# DRAFT generated by inst/build_metadata.R -- review before use.",
  sprintf("# Dataflow: %s", flow_id),
  "",
  "dim_order:",
  sprintf('  - "%s"', tolower(dims)),
  "",
  "hierarchy:"
)

for (d in dims) {
  codes <- base[base$dimension == d, ]
  out <- c(out, sprintf("  %s:", tolower(d)))
  parents <- codes$parent
  roots <- codes$code[is.na(parents) | !(parents %in% codes$code)]
  for (root in roots) {
    kids <- codes$code[!is.na(parents) & parents == root]
    if (length(kids)) {
      out <- c(out, sprintf("    '%s':", root),
               sprintf("      '%s': ~", kids))
    } else {
      out <- c(out, sprintf("    '%s': ~", root))
    }
  }
}

out <- c(out, "", "labels:", "  dimnames:")
for (d in dims) {
  out <- c(out, sprintf('    %s:', tolower(d)),
           sprintf('      %s: "TODO"', langs))
}
for (code in unique(base$code)) {
  out <- c(out, label_block(code, 4))
}

dir.create("data-raw", showWarnings = FALSE)
writeLines(out, "data-raw/metadata.draft.yaml")
message("Written: data-raw/metadata.draft.yaml (", length(dims), " dimensions, ",
        length(unique(base$code)), " codes)")
